name: Deploy React Frontend (Production)

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_VPS_IP }}
          username: ${{ secrets.PROD_VPS_USER }}
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/nexby-offcial-website

            echo "Switching to dev branch..."
            git checkout dev

            echo "Pulling latest code..."
            git pull origin dev

            echo "Installing dependencies..."
            npm i --force

            echo "Building project..."
            npm run build

            echo "Reloading nginx..."
            sudo systemctl reload nginx.service
